// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_AIAGENT_H_
#define _BEHAVIAC_AIAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class AIAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE AIAgent
///<<< END WRITING YOUR CODE
{
public:
	AIAgent();
	virtual ~AIAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(AIAgent, behaviac::Agent)

	public: int mMoveDir;

	private: void DoHMove(int d);

	private: int GetFaceEnermyX();

	private: int GetState();

	private: int GetX();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
