// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "AIAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

AIAgent::AIAgent()
{
	mMoveDir = 0;
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

AIAgent::~AIAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

void AIAgent::DoHMove(int d)
{
///<<< BEGIN WRITING YOUR CODE DoHMove
///<<< END WRITING YOUR CODE
}

int AIAgent::GetFaceEnermyX()
{
///<<< BEGIN WRITING YOUR CODE GetFaceEnermyX
	return 0;
///<<< END WRITING YOUR CODE
}

int AIAgent::GetState()
{
///<<< BEGIN WRITING YOUR CODE GetState
	return 0;
///<<< END WRITING YOUR CODE
}

int AIAgent::GetX()
{
///<<< BEGIN WRITING YOUR CODE GetX
	return 0;
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
