// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }

	inline void Set_AIAgent_mMoveDir(Agent* self, int value) { ((AIAgent*)self)->mMoveDir = value; };
	inline const void* Get_AIAgent_mMoveDir(Agent* self) { return &((AIAgent*)self)->mMoveDir; };

	inline void FunctionPointer_AIAgent_DoHMove(Agent* self, int d) { ((AIAgent*)self)->_Execute_Method_<METHOD_TYPE_AIAgent_DoHMove, void, int >(d); }
	inline int FunctionPointer_AIAgent_GetFaceEnermyX(Agent* self) { return (int)((AIAgent*)self)->_Execute_Method_<METHOD_TYPE_AIAgent_GetFaceEnermyX, int >(); }
	inline int FunctionPointer_AIAgent_GetState(Agent* self) { return (int)((AIAgent*)self)->_Execute_Method_<METHOD_TYPE_AIAgent_GetState, int >(); }
	inline int FunctionPointer_AIAgent_GetX(Agent* self) { return (int)((AIAgent*)self)->_Execute_Method_<METHOD_TYPE_AIAgent_GetX, int >(); }
	inline void FunctionPointer_AIAgent_LogMessage(char* param0) { AIAgent::LogMessage(param0); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
