// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_LOCKSTEP_AIAGENT_H_
#define _BEHAVIAC_LOCKSTEP_AIAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include "world.h"
#include "entity.h"
using namespace lockstep;
///<<< END WRITING YOUR CODE

namespace lockstep
{
///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT

///<<< END WRITING YOUR CODE

	class AIAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE AIAgent
///<<< END WRITING YOUR CODE
	{
	public:
		AIAgent();
		virtual ~AIAgent();

		BEHAVIAC_DECLARE_AGENTTYPE(lockstep::AIAgent, behaviac::Agent)

///<<< BEGIN WRITING YOUR CODE CLASS_PART

	public: inline void SetWorld(World* pWorld) { mPWorld = pWorld; }
public: inline void SetEntity(Entity* pEntity) { mPEntity = pEntity; }


	private: World* mPWorld;
	private: Entity* mPEntity;
///<<< END WRITING YOUR CODE
	};

///<<< BEGIN WRITING YOUR CODE NAMESPACE_UNINIT

///<<< END WRITING YOUR CODE
}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
